export const TICKET_TEMPLATE_EXPORT_DPI = 300;

export const TICKET_TEMPLATE_CANVAS_INCH_WIDTH = 8.5;
export const TICKET_TEMPLATE_CANVAS_INCH_HEIGHT = 2.75;

export const TICKET_TEMPLATE_CANVAS_PX_WIDTH =
  TICKET_TEMPLATE_CANVAS_INCH_WIDTH * TICKET_TEMPLATE_EXPORT_DPI;
export const TICKET_TEMPLATE_CANVAS_PX_HEIGHT =
  TICKET_TEMPLATE_CANVAS_INCH_HEIGHT * TICKET_TEMPLATE_EXPORT_DPI;

export const TICKET_TEMPLATE_NODE_KINDS = ["asset", "field", "qr"] as const;
